# Generated by Django 6.0.7 on 2026-07-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Cars',
        ),
    ]
