# Generated by Django 5.2.17 on 2026-08-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Dasturlash', 'Dasturlash'), ('Web Dasturlash', 'Web Dasturlash'), ('Grafik dizayn', 'Grafik dizayn'), ('Mobil dasturlash', 'Mobil dasturlash'), ("Sun'iy intellekt", "Sun'iy intellekt"), ('Robototexnika', 'Robototexnika')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matchinggroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
