# Generated by Django 6.0.3 on 2026-08-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_alter_cars_id_alter_course_id_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/'),
        ),
    ]
