# Generated by Django 5.2.17 on 2026-08-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_telegramcontact_verificationcode_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
