# Generated by Django 5.2.17 on 2026-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0013_alter_cars_id_alter_course_id_alter_matchinggroup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
